### PR TITLE
Shutdown gracefully at unhandled exception/rejection

### PR DESCRIPTION
**Pull request by oguzcankirmemis**
Signed-off-by: Oguzcan Kirmemis <oguzcan.kirmemis@gmail.com>

### CODE REVIEW

**Comment by oguzcankirmemis** [comment]
All there is left to do is to implement the logic at docker-compose to restart frontend if it crashes.

**Comment by wagmarcel** [comment]
Is it needed to change the wait-for-heartbeat.sh to make sure it is failing when the wait-for-heartbeat.js fails with exit  1?

**Comment by oguzcankirmemis** [comment]
> Is it needed to change the wait-for-heartbeat.sh to make sure it is failing when the wait-for-heartbeat.js fails with exit 1?

You are right, I was careless and did not look there, there were some argument options there, that is not used/needed any more (like -q: quiet or -s: strict), so I also removed these. Now the wait-for-heartbeat.sh truly checks the result of command and exits properly.

**Comment by oguzcankirmemis** [comment]
@wagmarcel, this can be merged now

**Review by wagmarcel — APPROVED** [review]

**Pull request merged**
