### PR TITLE
Upgrade node version from 4.8.3 to 6.13.1

### PR DESCRIPTION
**Pull request by chuan9**
Fix several dependencies issue, replace undefined with null for sequelize

### CODE REVIEW

**Comment by Cloud-Chen** [comment]
Can one of the admins verify this patch?

**Comment by chuan9** [comment]
@stevenbriscoe PTAL, thanks

**Comment by wagmarcel** [comment]
ok to test

**Comment by Cloud-Chen** [comment]
Can one of the admins verify this patch?

**Pull request merged**
