### PR TITLE
 Add getUnreadAlert API and upgrade ejs version to eliminate security vulnerabilities.

### PR DESCRIPTION
**Pull request by chuan9**
1. Add getUnreadAlert API
2. Upgrade ejs version to eliminate security vulnerabilities.
@stevenbriscoe PATL, thanks

### CODE REVIEW

**Comment by Cloud-Chen** [comment]
Can one of the admins verify this patch?

**Comment by chuan9** [comment]
@nevets963 Pls use node 6.13.1 version as we upgraded node version

**Comment by nevets963** [comment]
@chuan9 I pulled down your develop branch, so everything here was used and I see that I'm using the Node 6 base image and I built from scratch but I still get this error

**Comment by chuan9** [comment]
@nevets963 Can you tell me the steps to reproduce this issue? thanks

**Comment by nevets963** [comment]
@chuan9 Ah yes, you were it's because it was loading in the 'local' modules that were previously built for the previous node version. I will do some additional testing and come back.

**Pull request merged**
