### PR TITLE
Implement Jaeger Support For Frontend

### PR DESCRIPTION
**Pull request by oguzcankirmemis**
With this commit, all middlewares, all routes, and all postgres calls should be traced and the spans should be sent to jaeger-client.

Please test with jaeger ui, and report if something (like tags) needs to be changed, before it gets approved.

### CODE REVIEW

**Review by arkocal — DISMISSED** [review]
Great! Works on kubernetes too!

**Comment by arkocal** [comment]
Oh, please sign your commits (or at least final commit) (git commit -s -S) (see `CONTRIBUTING.txt`) and force push over the old ones. 
@wagmarcel We stillt need to remove the auto check here as well though, for merging.

**Comment by wagmarcel** [comment]
@arkocal  ok, autocheck removed.

**Comment by oguzcankirmemis** [comment]
@arkocal @wagmarcel ok, I have signed the last commit, you can merge it now.

**Review by arkocal — APPROVED** [review]
Lets hunt for performance issues!

**Pull request merged**
