### PR TITLE
Grafana Integration ...

### PR DESCRIPTION
**Pull request by oguzcankirmemis**
grafana: added reverse proxies for grafana and opentsdb
dashboard: added grafana icon to display and handle grafana integration at charts
Gruntfile.js: added grafana directory for linter
package.json: added dependencies for reverse proxy

Signed-off-by: Oguzcan Kirmemis <oguzcan.kirmemis@gmail.com>

### CODE REVIEW

**Comment by wagmarcel** [comment]
@oguzcankirmemis - the needed OpenTSDB/S3 patch is currently reviewed in platform-launcher. When it gets approved, OpenTSDB will be the default backend for numbers (and S3 for strings and binary data). Once this is done we will work to integrate your patches. Please rebase it to be prepared it has conflicts meanwhile.

**Comment by oguzcankirmemis** [comment]
> @oguzcankirmemis - the needed OpenTSDB/S3 patch is currently reviewed in platform-launcher. When it gets approved, OpenTSDB will be the default backend for numbers (and S3 for strings and binary data). Once this is done we will work to integrate your patches. Please rebase it to be prepared it has conflicts meanwhile.

Will do, there is also one thing I want to change, namely the client-side code 'guesses' the port at [here](https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/4c96dd3479977e2c91050c72d71fd5e68f2f151a/public-interface/dashboard/public/js/controllers/charts/charts.js#L647), which of course should be changed, my mistake for not realising before.

**Comment by oguzcankirmemis** [comment]
@wagmarcel done rebasing and retriggered tests, this needs manual checking though, as e2e test does not cover grafana.

Some changes after the initial PR that are worth mentioning:

-  Grafana image size was high resolution, now reduced to a logo size
-  Dashboard code no longer 'guesses' the port for grafana proxy, nginx does this instead (should be easy to implement the same behavior in kubernetes)
- Every frontend instance gets its unique grafana API Token now, if two of them shares by chance the same id, then they share this id (note that this case is very unlikely since uuid module will surely not produce the same id twice but one can never be certain). This change is introduced to support kubernetes.

**Comment by oguzcankirmemis** [comment]
@wagmarcel e2e-test failed because it needs the OISP_GRAFANA_CONFIG environment variable, which is introduced at [#131](https://github.com/Open-IoT-Service-Platform/platform-launcher/pull/131), you can check the log of the frontend if this is indeed the case or if it was something else let me know and I will fix it (though with the PR at platform-launcher it works locally stable by me).

**Review by wagmarcel — APPROVED** [review]

**Pull request merged**
