### PR TITLE
Upgrade node version from v4.8.3 to v6.13.1

### PR DESCRIPTION
**Pull request by chuan9**
upgrade node version and fix failed test cases.

### CODE REVIEW

**Comment by Cloud-Chen** [comment]
Can one of the admins verify this patch?

**Comment by chuan9** [comment]
@stevenbriscoe PTAL, thanks

**Comment by Cloud-Chen** [comment]
Ok to test

**Comment by nevets963** [comment]
@chuan9 This is approved. Can you re-submit this but for the 'develop' branch?

**Pull request merged**
